### ISSUE TITLE
Unsupport ioctl flag: TIOCGPGRP

### ISSUE THREAD

**Issue by ex0dus-0x** [pkmoore/syscallreplay#3]
## `strace` segment
```
1940  ioctl(0, TIOCGPGRP, [-1214129095]) = 0
1940  getpgrp()                         = 1935
1940  write(2, "503 Service Unavailable\n", 24) = 24
1940  close(3)                          = 0
1940  stat64("index.html", 0xbff676ec)  = -1 ENOENT (No such file or directory)
1940  _newselect(5, [4], NULL, NULL, {tv_sec=900, tv_usec=0}) = 1 (in [4], left {tv_sec=900, tv_usec=0})
```
## Traceback
```
Traceback (most recent call last):
  File "./inject.py", line 401, in main
    syscallreplay.entering_syscall)
  File "./inject.py", line 98, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "./inject.py", line 306, in handle_syscall
    handlers[(syscall_id, entering)](syscall_id, syscall_object, pid)
  File "/home/testbed/isolate/rrapper/crashsim/local/lib/python2.7/site-packages/syscallreplay/kernel_handlers.py", line 475, in ioctl_entry_handler
    raise NotImplementedError('Unsupported ioctl command')
NotImplementedError: Unsupported ioctl command
Failed to complete trace
Injector for event:rec_pid 929:1940 failed
```

**Comment by alyptik** [comment]
Also for anyone wondering the [-1214129095] is just some uninitialized garbage value. If the ioctl() syscall itself doesn't error but the actual ioctl does, the outbuffer isn't modified so it will just be some random indeterminate value
